<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Karthick" failures="1" tests="4" name="Workflow Test" time="34.016" errors="0" timestamp="2024-08-20T12:37:07 GMT+05:30">
  <testcase classname="tests.SignupPageTest" name="signupTest" time="6.65"/>
  <testcase classname="tests.LoginPageTest" name="loginTest" time="8.426"/>
  <testcase classname="tests.CartFailureTest" name="testCartIconAfterRemovingProduct" time="10.992">
    <failure type="java.lang.AssertionError" message="Cart icon should display 0 after removing the product expected [0] but found [1]">
      <![CDATA[java.lang.AssertionError: Cart icon should display 0 after removing the product expected [0] but found [1]
at tests.CartFailureTest.testCartIconAfterRemovingProduct(CartFailureTest.java:64)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1570)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- testCartIconAfterRemovingProduct -->
  <testcase classname="tests.ProductBuyTest" name="addProductTest" time="21.052"/>
</testsuite> <!-- Workflow Test -->
